{% set version = "1.1-7" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ic.infer
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ic.infer_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ic.infer/ic.infer_{{ version }}.tar.gz
  sha256: 055329e68eb3b9ab5248a58ede2c6f45faa8b6678c938b8e287c4db0b53d213f

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:

  host:
    - r-base
    - r-boot
    - r-kappalab
    - r-mvtnorm
    - r-quadprog
  run:
    - r-base
    - r-boot
    - r-kappalab
    - r-mvtnorm
    - r-quadprog

test:
  commands:
    - $R -e "library('ic.infer')"           # [not win]
    - "\"%R%\" -e \"library('ic.infer')\""  # [win]

about:
  home: http://prof.beuth-hochschule.de/groemping/
  license: GPL (>= 2)
  summary: Implements inequality constrained inference. This includes parameter estimation in normal (linear) models under linear equality and inequality constraints, as well as normal likelihood ratio tests involving inequality-constrained hypotheses. For inequality-constrained linear models, averaging over R-squared for
    different orderings of regressors is also included.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
