appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: NKQANhx4ZmzT/RptZ4yk0xjSNkh+79PjsJpgHo+nVnOM3cCch/NBLm2egdfyKA11LJhz1e9JXfOx9CVAxtmV6SvD7V88GenN5HsSrnbhOaja1BAYC3zPVNGqoxZEIY1lub3pSKUfccpbhj3FUTNcuSLwdR2odFFatifZD+nAI5Cl/V64HR1HDboG76qvvnKtZTzRNbwEtU5AuuMbfIUTXfFV8TWBGtPISUqzQ2yu7GzzYDYZW1Yr9AByZxf4N8nkXIBukMYIukZJYLWFY5aBweruZyvPOBhf0dBEpjBHlh/a0aFMWUO2h2J4nlma3YMPIs2MCFupEYrjuPTN8lzZph2bxi69N1jvP5PfLcE0B4o4FcHTAooBlYEx+HBAjB0BjSxQU7pCBDjLG25Ln0VDKtu8ZrB82IM0Zn/C5DnvwqZzJClPjsXbJ8YDvppne/6kylYLTamQsMAPSB+PYuRfIFO0EW/CMOCDibaXv4QXfY6WfVHIwxJJqHIu0ivdOOcoA12mSCWJMtWTnydzat6fi0bqXaP5I7Uh30Iew6PcUYB/jnEQZ9JOrsusHRTvxSsDUj8EnLirmBGLTecL+i/MGmIjZE1jPJ+JLUramjtorr15ZXhxUa0RP6ryGBoJjIPtYIjlG8Nro65gZh/q/XhcqdvKFP14A0i4AwgOcksKZTo=
